name: Python

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Run unified2orchestra
      run: python3 orchestratransposer.py unified/FixRepository.xml unified/FIX.Latest_en_phrases.xml -f unif -t orch -o orchestra-p.xml
    - name: Run orchestra2unified
      run: python3 orchestratransposer.py orchestra-p.xml -f orch -t unif -o FixRepository-p.xml FIX.Latest_en_phrases-p.xml 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: orchestra-python
        path: "*-p.xml"
    - name: Upload Process Log
      uses: actions/upload-artifact@v2
      with:
        name: log-python
        path: orchestra.log  
